### ISSUE TITLE
Mapillary Inference Size

### ISSUE THREAD

**Issue by jiangzhengkai** [HeliosZhao/SHADE#1]
I notice you use 1536 x 1536 for mapillary inference, why choose such size?

In addition, you also resize label, which is not a common way for segmentation evaluation, why choose this way?

**Comment by HeliosZhao** [comment]
We follow RobustNet for this, which aims at solving the different resolutions of Mapillary. You may refer to [this issue].(https://github.com/shachoi/RobustNet/issues/24#issuecomment-1165505545)
