### ISSUE TITLE
GTA5 training size choise

### ISSUE THREAD

**Issue by jiangzhengkai** [HeliosZhao/SHADE#2]
RobustNet only uses GTA5 training set for experiments, but you use full set which is not fair to compare? Why choose this way?

**Comment by HeliosZhao** [comment]
Thanks for your interest in our work.
As mentioned in our paper (Sec.4.1 **Protocols**), we use different training datasets for a fair comparison. 
Specifically, when using ResNet-50, we use the GTAV training set, which is the same as RobustNet. When using ResNet-101, we use the whole set for training, which is the same as FSDR, and we also reproduce RobustNet with ResNet-101 and whole training set.
