### ISSUE TITLE
FPS visualization

### ISSUE THREAD

**Issue by wwwmj23** [HeliosZhao/SHADE#4]
Hello!Thank you very much for disclosing the code.
 May I ask if it is convenient for you to publish the rendering code for FPS sampling? (Similar to FIG.3 in the article), or can you tell me how to handle channel dimensions when visualizing, whether to visualize the mean and variance of 64 channels in each graph or to visualize a separate channel in each graph?
Looking forward to your reply, thank you

**Comment by HeliosZhao** [comment]
Hi, we concatenate the mean and standard deviation (each of them is a 64-dimension vector) together to a 128-dimension vector. Then t-SNE is used to reduce the dimension to 2, and the dimension-reduced vector is plotted.
